- platform: command_line
  switches:
    print_attestation:
      command_on: "lp -h127.0.0.1 -d HP_ENVY_5000_series /stick/28-11-2020-attestation-de-deplacement-derogatoire"
      command_off: "cancel -h127.0.0.1 -a"
      command_state: "lpstat -h127.0.0.1 -p HP_ENVY_5000_series | grep -c -v idle"
      friendly_name: Print Attestation
    print_attestation_iulia:
      command_on: "lp -h127.0.0.1 -d HP_ENVY_5000_series /stick/Attestation_Iulia.pdf"
      command_off: "cancel -h127.0.0.1 -a"
      command_state: "lpstat -h127.0.0.1 -p HP_ENVY_5000_series | grep -c -v idle"
      friendly_name: Print Attestation Iulia
    print_attestation_pascal:
      command_on: "lp -h127.0.0.1 -d HP_ENVY_5000_series /stick/Attestation_Pascal.pdf"
      command_off: "cancel -h127.0.0.1 -a"
      command_state: "lpstat -h127.0.0.1 -p HP_ENVY_5000_series | grep -c -v idle"
      friendly_name: Print Attestation Pascal

