title: Light
views:
  - title: Light
    cards:
      - type: entities
        entities:
          - entity: light.color_temperature_light_18
            name: Lampadaire industrielle chambre
          - entity: light.color_temperature_light_8
            name: Lampe de bureau
          - entity: light.dimmable_light_3
            name: Lampe cuisine
          - entity: light.dimmable_light_2
            name: Lampe bedroom
    
    
        title: Ampoules
        show_header_toggle: true
      - type: entities
        entities:
        - entity: light.color_temperature_light_4
        - entity: light.color_temperature_light_17
        - entity: light.color_temperature_light_11
        title: Salon
    
