title: Meteo
views:
  - title: Meteo
    badges:
      - sensor.bordeaux_uv
      - sensor.xiron_6602_bat
      - sensor.xiron_6901_bat
      - sensor.baldr_5602_bat
      - sensor.33_weather_alert
    cards:
      - type: weather-forecast
        entity: weather.bordeaux
      - type: iframe
        url: https://www.meteo-biarritz.com/rain-map?zoom=7&lat=44.83000&lon=-0.57000&showTitle=1
        aspect_ratio: 50%
      - type: iframe
        url: https://aqicn.org/city/france/aquitaine/bordeaux/bastide/fr/m/
        aspect_ratio: 85%
      - type: picture
        image: https://www.pollens.fr/generated/vigilance_map.png
        title: Pollen
        tap_action:
          action: url
          url_path: https://www.pollens.fr/
      - type: history-graph
        hours_to_show: 8
        entities:
        - sensor.airquality_35_pm25
        - sensor.airquality_37_pm25
        - sensor.xiron_6602_temp
        - sensor.xiron_6901_temp
        - sensor.baldr_5602_temp
        - sensor.auriol_00ee_temp
    
