path: security
title: Security
icon: mdi:shield-account
badges:
  - type: entity-filter
    entities:
      - entity: sensor.baldr_3602_bat
      - entity: sensor.baldr_b301_bat
      - entity: sensor.xiron_3301_bat
      - entity: sensor.xiron_6f01_bat
      - entity: sensor.xiron_0102_bat
      - entity: sensor.xiron_1e03_bat
    state_filter:
      - operator: "!="
        value: "ok"

cards:
  - type: entities
    show_header_toggle: false
    entities:
      - entity: binary_sensor.chuango_9b7539_02
        name: Fumée
      - entity: binary_sensor.ev1527_03c652_05
        name: Fuite
      - entity: binary_sensor.front_door_motion
        name: Mouvement à l'entrée
      - entity: sensor.xiron_3301_temp
        name: Frigo
      - entity: binary_sensor.ev1527_082b13_06
        name: Porte
      - entity: input_boolean.engage_alarm
        name: Alarme
