path: security
title: Security
icon: mdi:shield-account
badges:
  - type: entity-filter
    entities:
      - entity: sensor.baldr_3602_bat
      - entity: sensor.baldr_b301_bat
      - entity: sensor.xiron_3301_bat
      - entity: sensor.xiron_6f01_bat
      - entity: sensor.xiron_0102_bat
      - entity: sensor.xiron_1e03_bat
    state_filter:
      - operator: "!="
        value: "ok"
  - type: entity-filter
    entities:
      - entity: sensor.openclose_4_battery_level
      - entity: sensor.openclose_6_battery_level
      - entity: sensor.openclose_7_battery_level
      - entity: sensor.openclose_8_battery_level
      - entity: sensor.openclose_9_battery_level
      - entity: sensor.openclose_10_battery_level
      - entity: sensor.e5823_niveau_de_batterie_2
        name: Velo
    state_filter:
      - operator: "<"
        value: 30
cards:
  - type: entities
    show_header_toggle: false
    entities:
      - entity: binary_sensor.chuango_9b7539_02
        name: Fumée
      - entity: binary_sensor.ev1527_03c652_05
        name: Fuite
      - name: Garden start
        entity: light.ev1527_0dce12_08
      - name: Garden emergency stop        
        entity: light.ev1527_0dce12_04  
      - entity: sensor.e5823_niveau_de_batterie_2
        name: Velo
      - entity: binary_sensor.front_door_motion
        name: Mouvement à l'entrée
      - entity: sensor.xiron_3301_temp
        name: Frigo
      - entity: binary_sensor.ev1527_082b13_06
        name: Porte
      - entity: binary_sensor.openclose_4
        name: Porte
      - entity: binary_sensor.openclose_6
        name: Verou
      - entity: binary_sensor.openclose_7
        name: Frigo
      - entity: binary_sensor.openclose_8
        name: Porte fenetre
      - entity: binary_sensor.openclose_9
        name: Fenetre Gauche
      - entity: binary_sensor.openclose_10
        name: Fenetre Droite
      - entity: input_boolean.engage_alarm
        name: Alarme
  - type: glance
    show_header_toggle: false
    entities:
      - entity: switch.print_attestation
        name: Print Attestation
        icon: mdi:printer
        show_state: true
      - entity: switch.print_attestation_iulia
        name: Attestation Iulia
        icon: mdi:printer
        show_state: true
      - entity: switch.print_attestation_pascal
        name: Attestation Pascal
        icon: mdi:printer
        show_state: true

