#automation:
- alias: Hand made alarm
  trigger:
    platform: state
    entity_id: binary_sensor.ev1527_082b13_06, binary_sensor.eurodomest_0c20ef_02, binary_sensor.eurodomest_2c20ef_05
  condition:
    condition: state
    entity_id: input_boolean.engage_alarm
    state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.engage_alarm
    - service: switch.turn_on
      entity_id: switch.hdmi_2_source_button
    - service: media_extractor.play_media
      entity_id: media_player.chromecast1919
      data:
        media_content_id: "https://www.youtube.com/watch?v=b0kib2o4hmA"
        media_content_type: video/youtube

- alias: Signaux Alternatif (On) frigo
  trigger:
    platform: state
    entity_id: binary_sensor.ev1527_0c44ea_0e
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.eurodomest_23bb15_00

- alias: Signaux Alternatif (Off) frigo
  trigger:
    platform: state
    entity_id: binary_sensor.ev1527_0c44ea_07
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.eurodomest_23bb15_00


- alias: Motion at front door
  trigger:
    platform: state
    entity_id: binary_sensor.eurodomest_0c20ef_02, binary_sensor.eurodomest_2c20ef_05
  condition:
    condition: state
    entity_id: input_boolean.front_door_motion
    state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.front_door_motion

- alias: Reset motion counter
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_motion
    to: 'on'
  action:
    - delay:
        minutes: 1
    - service: input_boolean.turn_off
      entity_id: input_boolean.front_door_motion

- alias: Smoke
  trigger:
    platform: state
    entity_id: binary_sensor.chuango_9b7539_02
    to: 'on'
  action:
    - service: notify.notify
      data:
        title: "Fumée"
        message: "Le detecteur indique de la fumée"
    - service: persistent_notification.create
      data:
        title: "Fumée"
        message: "Le detecteur indique de la fumée"

- alias: Water
  trigger:
    platform: state
    entity_id: binary_sensor.ev1527_03c652_05
    to: 'on'
  action:
    - service: notify.notify
      data:
        title: "Fuite"
        message: "Le detecteur indique de l'humiditée"
    - service: persistent_notification.create
      data:
        title: "Fuite"
        message: "Le detecteur indique de l'humiditée"
    - service: switch.turn_on
      entity_id: switch.hdmi_2_source_button
    - service: media_extractor.play_media
      entity_id: media_player.chromecast1919
      data:
        media_content_id: "http://www.haute-garonne.gouv.fr/content/download/23659/166500/file/Corne%20de%20brume.mp3"
        media_content_type: 'audio/mp3'

- alias: Frigo
  trigger:
    platform: numeric_state
    entity_id: sensor.xiron_3301_temp
    above: 15
  action:
    - service: notify.notify
      data:
        title: "Frigo"
        message: "La temperature du frigo est de {{ states('sensor.xiron_3301_temp') }}"
    - service: persistent_notification.create
      data:
        title: "Frigo"
        message: "La temperature du frigo est de {{ states('sensor.xiron_3301_temp') }}"
