
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

rflink:
  port: /dev/ttyUSB0
  ignore_devices:
    - xiron_3301_update_time
    - baldr_3602_update_time
    - baldr_b301_update_time
    - xiron_6f01_update_time
    - xiron_0102_update_time
    - xiron_1e03_update_time
device_tracker:
  - platform: bbox


lovelace:
  mode: yaml

light:
  - platform: rflink
    automatic_add: true
    devices:
      maclean_582f_01: {}
      maclean_582f_02: {}
      maclean_582f_03: {}
      maclean_582f_04: {}
      unitec_2be2_00: {}
      unitec_2be2_01: {}
      unitec_2be2_02: {}
      unitec_2be2_03: {}
      unitec_2be2_04: {}
      newkaku_0000c6c2_1:
        type: hybrid
      newkaku_02a48800_2:
        type: hybrid
      eurodomest_23bb15_00:
        aliases:
        - eurodomest_23bb15_01
sensor:
  - platform: rflink
    automatic_add: true
    devices:
      xiron_3301_temp:
        sensor_type: temperature
      xiron_3301_bat:
        sensor_type: battery
      xiron_3301_hum:
        sensor_type: humidity
      baldr_3602_temp:
        sensor_type: temperature
      baldr_3602_bat:
        sensor_type: battery
      baldr_3602_hum:
        sensor_type: humidity
      baldr_b301_temp:
        sensor_type: temperature
      baldr_b301_hum:
        sensor_type: humidity
      baldr_b301_bat:
        sensor_type: battery
      xiron_6f01_temp:
        sensor_type: temperature
      xiron_6f01_hum:
        sensor_type: humidity
      xiron_6f01_bat:
        sensor_type: battery
      xiron_0102_temp:
        sensor_type: temperature
      xiron_0102_hum:
        sensor_type: humidity
      xiron_0102_bat:
        sensor_type: battery
      xiron_1e03_temp:
        sensor_type: temperature
      xiron_1e03_hum:
        sensor_type: humidity
      xiron_1e03_bat:
        sensor_type: battery
  - platform: template
    sensors:
      air_pressure_template:
        friendly_name: 'Air Pressure'
        value_template: "{{ state_attr('weather.home','pressure') | default('1013') }}"
        unit_of_measurement: hPa
  - platform: derivative
    source: sensor.baldr_b301_temp
    name: baldr_b301_delta
    round: 1
    unit: 'Celsius'
    time_window: "00:15:00"
  - platform: filter
    name: baldr_b301_delta_avg
    entity_id: sensor.baldr_b301_delta
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
  - platform: bbox
    monitored_variables:
      - down_max_bandwidth
      - up_max_bandwidth
      - current_down_bandwidth
      - current_up_bandwidth
      - uptime
      - number_of_reboots
  - platform: template
    sensors:
      bordeaux_temperature:
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('weather.bordeaux_2', 'temperature') }}"
      bordeaux_humidity:
        unit_of_measurement: '%'
        value_template: "{{ state_attr('weather.bordeaux_2', 'humidity') }}"
      home_temperature:
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('weather.home', 'temperature') }}"
      home_humidity:
        unit_of_measurement: '%'
        value_template: "{{ state_attr('weather.home', 'humidity') }}"


binary_sensor:
  - platform: rflink
    devices:
      ev1527_082b13_06:
        device_class: door
        off_delay: 60
      ev1527_03c652_05: 
        off_delay: 150
        device_class: moisture
      chuango_9b7539_02:
        device_class: smoke
        off_delay: 150
      eurodomest_0c20ef_02:
        device_class: motion
        force_update: true
      eurodomest_2c20ef_05:
        device_class: motion
        force_update: true
      ev1527_0c44ea_0b:
        force_update: true
        off_delay: 60
      ev1527_0c44ea_07:
        force_update: true
        off_delay: 60
      ev1527_0c44ea_0e:
        force_update: true
        off_delay: 60
  - platform: template
    sensors:
      front_door_motion:
        device_class: motion
        value_template: "{{ is_state('input_boolean.front_door_motion', 'on') }}"

input_boolean: 
  front_door_motion:
    name: Mouvement à l'entrée
  engage_alarm:
    name: Alame enclenchée

logger:
  default: error
  #  logs:
  #    rflink: debug
  #    homeassistant.components.rflink: debug

media_extractor:


# Example configuration.yaml entry
#google_assistant:
#  project_id: smarthome-4b89e 
#  service_account: !include smarthome-a56cd02dc1d3.json
#  report_state: true
#  expose_by_default: true
#  entity_config:
#    switch.gt_9000_rf1_power_button:
#      name: lumiere_cuisine
#
#
