
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Example configuration.yaml entry
#google_assistant:
#  project_id: smarthome-4b89e 
#  service_account: !include smarthome-a56cd02dc1d3.json
#  report_state: true
#  expose_by_default: true
#  entity_config:
#    switch.gt_9000_rf1_power_button:
#      name: lumiere_cuisine
#
