
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: storage
  dashboards:
    lovelace-remote:
      mode: yaml
      title: Remote
      icon: mdi:remote
      show_in_sidebar: true
      filename: lovelace/esp07s_iremote.yaml
    lovelace-light:
      mode: yaml
      title: Light
      icon: mdi:lightbulb
      show_in_sidebar: true
      filename: lovelace/light.yaml
    lovelace-meteo:
      mode: yaml
      title: Meteo
      icon: mdi:weather-partly-cloudy
      show_in_sidebar: true
      filename: lovelace/meteo.yaml



http:
  use_x_forwarded_for: true
  trusted_proxies:
   - 10.195.236.1
   - 192.168.1.36
   - 192.168.1.51
   - 127.0.0.1
   - ::1

rflink:
  port: /dev/ttyUSB0

light: !include_dir_merge_list lights
sensor: !include_dir_merge_list sensors

#logger:
#  default: error
#  logs:
#    rflink: debug
#    homeassistant.components.rflink: debug
