
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations
scene: !include_dir_merge_list scenes
script: !include scripts.yaml

rflink:
  port: /dev/ttyUSB0
  ignore_devices:
    - xiron_3301_update_time
    - baldr_3602_update_time
    - baldr_b301_update_time
    - xiron_6f01_update_time
    - xiron_0102_update_time
    - xiron_1e03_update_time
device_tracker:
  - platform: bbox

glances:
  - host: 127.0.0.1
    name: first
  - host: second
    name: second
  - host: third
    name: third
  - host: matrix
    name: matrix
  - host: jitsi
    name: jitsi
  - host: frontend
    name: frontend
  - host: 10.249.107.1
    name: gateway

lovelace:
  mode: yaml

light: !include_dir_merge_list lights
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
switch: !include_dir_merge_list switches
input_boolean: !include_dir_merge_named input_booleans

logger:
  default: error
  #  logs:
  #    rflink: debug
  #    homeassistant.components.rflink: debug

media_extractor:

# Example configuration.yaml entry
#google_assistant:
#  project_id: smarthome-4b89e 
#  service_account: !include smarthome-a56cd02dc1d3.json
#  report_state: true
#  expose_by_default: true
#  entity_config:
#    switch.gt_9000_rf1_power_button:
#      name: lumiere_cuisine
#
#
