
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

rflink:
  port: /dev/ttyUSB0
  ignore_devices:
    - xiron_3301_update_time
    - baldr_3602_update_time

lovelace:
  mode: yaml

light:
  - platform: rflink
    automatic_add: true
    devices:
      maclean_582f_01: {}
      maclean_582f_02: {}
      maclean_582f_03: {}
      maclean_582f_04: {}
      unitec_2be2_00: {}
      unitec_2be2_01: {}
      unitec_2be2_02: {}
      unitec_2be2_03: {}
      unitec_2be2_04: {}
sensor:
  - platform: rflink
    automatic_add: true
    devices:
      xiron_3301_temp:
        sensor_type: temperature
      xiron_3301_bat:
        sensor_type: battery
      xiron_3301_hum:
        sensor_type: humidity
      baldr_3602_temp:
        sensor_type: temperature
      baldr_3602_bat:
        sensor_type: battery
      baldr_3602_hum:
        sensor_type: humidity

# Example configuration.yaml entry
#google_assistant:
#  project_id: smarthome-4b89e 
#  service_account: !include smarthome-a56cd02dc1d3.json
#  report_state: true
#  expose_by_default: true
#  entity_config:
#    switch.gt_9000_rf1_power_button:
#      name: lumiere_cuisine
#
#
