title: My Awesome Home
views:
  - !include lovelace/remote.yaml
  - !include lovelace/meteo.yaml
  - !include lovelace/covid.yaml
  - !include lovelace/light.yaml
  - !include lovelace/monitoring.yaml
  - !include lovelace/security.yaml
