title: My Awesome Home
views:
  - path: map
    title: Map
    panel: true
    icon: mdi:google-map
    cards:
      - type: map
        title: Map
        entities:
          - entity: person.pascal
          - entity: person.iulia
          - entity: device_tracker.tilt
        hours_to_show: 12
