title: My Awesome Home
views:
  - path: map
    title: Map
    panel: true
    icon: mdi:google-map
    visible:
      - user: e326af935b6f48188b4f820973e7341d                                
      - user: 89e84b4c25c24a689fca9b5ab7d50889  
    cards:
      - type: map
        title: Map
        entities:
          - entity: person.pascal
          - entity: person.iulia
          - entity: person.velo
        hours_to_show: 12
