- alias: 'Set cube state'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: mi_magic_cube
  condition:
    condition: template
    value_template: >
      {% set valid_events = [3, 4, 5, 6] %}
      {{ trigger.event.data.gesture in valid_events }}
  action:
  - service: input_number.set_value
    data:
      entity_id: input_number.cube
      value: "{{ ((trigger.event.data.event | int) / 1000)|round() }}"
