- alias: 'Toggle lamp Gauche Gauche'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: transmitter_2_gang
        event: 1004
  action:
    - service: light.turn_off
      entity_id: light.dimmable_light_2
    - service: light.turn_off                                                                                                                                                       
      entity_id: light.color_temperature_light_7 
    - service: light.turn_off                                                                                                                                                       
      entity_id: light.color_temperature_light_8 
    - service: light.turn_off
      entity_id: light.maclean_582f_02
    - service: light.turn_off
      entity_id: light.maclean_582f_03
