- alias: 'Toggle lamp Droite'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: transmitter_2_gang
      event: 2002
  action:
    - service: light.toggle
      entity_id: light.unitec_2be2_01
    - service: light.toggle
      entity_id: light.unitec_2be2_02
    - service: light.toggle
      entity_id: light.color_temperature_light_4
    - service: light.toggle
      entity_id: light.dimmable_light_3
