- alias: 'Toggle lamp Gauche'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: transmitter_2_gang
      event: 1002
  action:
    - service: light.toggle
      entity_id: light.dimmable_light_2
    - service: light.toggle
      entity_id: light.dimmable_light_3 
    - service: light.toggle
      entity_id: light.maclean_582f_02
    - service: light.toggle
      entity_id: light.maclean_582f_03
