- alias: 'Toggle lamp Turn ON Tradfri'
  initial_state: 'on'                                                                                                                                                               
  trigger:                                                                                                                                                                          
    - platform: event                                                                                                                                                               
      event_type: deconz_event                                                                                                                                                      
      event_data:                                                                                                                                                                   
        id: tradfri_remote_control                                                                                                                                                   
        event: 3002                                                                                                                                                                 
  action:   
    - service: scene.turn_on
      entity_id: scene.theater
