- alias: 'Tradfri (<)'
  initial_state: 'on'
  condition:
    - condition: template
      value_template: "{{ state_attr('light.color_temperature_light_4', 'color_temp') | int > 230 }}"
  trigger:                                                                                                                                                                          
    - platform: event                                                                                                                                                               
      event_type: deconz_event                                                                                                                                                      
      event_data:                                                                                                                                                                   
        id: tradfri_remote_control                                                                                                                                                   
        event: 4002                                                                                                                                                                 
  action:                                                                                                                                                                           
    - service: light.turn_on                                                                                                                                                       
      entity_id: light.color_temperature_light_4
      data_template:
        color_temp: "{{state_attr('light.color_temperature_light_4', 'color_temp') | int - 50 }}"
