- alias: 'Tradfri (^)'
  initial_state: 'on'                                                                                                                                                               
  trigger:                                                                                                                                                                          
    - platform: event                                                                                                                                                               
      event_type: deconz_event                                                                                                                                                      
      event_data:                                                                                                                                                                   
        id: tradfri_remote_control                                                                                                                                                   
        event: 2002                                                                                                                                                                 
  action:                                                                                                                                                                           
    - service: light.turn_on                                                                                                                                                       
      entity_id: light.color_temperature_light_4
      data_template:
        brightness: "{{state_attr('light.color_temperature_light_4', 'brightness') | int + 60 }}"
    - service: light.turn_on
      entity_id: light.dimmable_light_2
      data_template:
        brightness: "{{state_attr('light.dimmable_light_2', 'brightness') | int + 60 }}"
    - service: light.turn_on
      entity_id: light.dimmable_light_3
      data_template:
        brightness: "{{state_attr('light.dimmable_light_3', 'brightness') | int + 60 }}"

