- alias: 'Toggle lamp Turn ON Tradfri'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 1002
  action:
    - service: light.toggle
      entity_id: light.dimmable_light_2
    - service: light.toggle
      entity_id: light.color_temperature_light_4
    - service: light.toggle
      entity_id: light.dimmable_light_3

