- alias: 'Toggle lamp Turn ON to OFF TradfriMID'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 1002
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control_2
        event: 1002
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control_3
        event: 1002
    - platform: event
      event_type: deconz_event    
      event_data:
        id: tradfri_remote_control_4
        event: 1002 
  condition:
    condition: or
    conditions:
       - condition: state
         entity_id: light.unitec_2be2_01
         state: 'on'
       - condition: state
         entity_id: light.unitec_2be2_02
         state: 'on'
       - condition: state
         entity_id: light.dimmable_light_2
         state: 'on'
       - condition: state
         entity_id: light.color_temperature_light_4
         state: 'on'
       - condition: state
         entity_id: light.color_temperature_light_7
         state: 'on'
       - condition: state
         entity_id: light.maclean_582f_02
         state: 'on'
       - condition: state
         entity_id: light.maclean_582f_03
         state: 'on'
       - condition: state
         entity_id: light.unitec_3aa3_01
         state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.unitec_2be2_01
    - service: light.turn_off
      entity_id: light.unitec_2be2_02
    - service: light.turn_off
      entity_id: light.dimmable_light_2
    - service: light.turn_off
      entity_id: light.color_temperature_light_4
    - service: light.turn_off
      entity_id: light.color_temperature_light_7
    - service: light.turn_off
      entity_id: light.maclean_582f_02
    - service: light.turn_off
      entity_id: light.maclean_582f_03
    - service: light.turn_off
      entity_id: light.unitec_3aa3_01
- alias: 'Toggle lamp Turn OFF to ON TradfriMID'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 1002
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control_2
        event: 1002
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control_3
        event: 1002
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control_4
        event: 1002
  condition:
    condition: and
    conditions:
       - condition: state
         entity_id: light.unitec_2be2_01
         state: 'off'
       - condition: state
         entity_id: light.unitec_2be2_02
         state: 'off'
       - condition: state
         entity_id: light.dimmable_light_2
         state: 'off'
       - condition: state
         entity_id: light.color_temperature_light_4
         state: 'off'
       - condition: state
         entity_id: light.color_temperature_light_7
         state: 'off'
       - condition: state
         entity_id: light.maclean_582f_02
         state: 'off'
       - condition: state
         entity_id: light.maclean_582f_03
         state: 'off'
       - condition: state
         entity_id: light.unitec_3aa3_01
         state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.dimmable_light_2
    - service: light.turn_on
      entity_id: light.color_temperature_light_4
    - service: light.turn_on
      entity_id: light.color_temperature_light_7
