- platform: rflink
  automatic_add: true
  devices:
    xiron_3301_temp:
      sensor_type: temperature
    xiron_3301_bat:
      sensor_type: battery
    xiron_3301_hum:
      sensor_type: humidity
    baldr_b301_temp:
      sensor_type: temperature
    baldr_b301_hum:
      sensor_type: humidity
    baldr_b301_bat:
      sensor_type: battery
    baldr_b303_temp:
      sensor_type: temperature
    baldr_b303_hum:
      sensor_type: humidity
    baldr_b303_bat:
      sensor_type: battery
    xiron_0102_temp:
      sensor_type: temperature
    xiron_0102_hum:
      sensor_type: humidity
    xiron_0102_bat:
      sensor_type: battery
    xiron_0a01_temp:
      sensor_type: temperature
    xiron_0a01_bat:
      sensor_type: battery
    xiron_0a01_hum:
      sensor_type: humidity
    xiron_2102_temp:
      sensor_type: temperature
    xiron_2102_bat:
      sensor_type: battery
    xiron_2102_hum:
      sensor_type: humidity
    xiron_6303_temp:
      sensor_type: temperature
    xiron_6303_bat:
      sensor_type: battery
    xiron_6303_hum:
      sensor_type: humidity
    globaltronics_00ee_temp:
      sensor_type: temperature
    globaltronics_00ee_hum:
      sensor_type: humidity
    globaltronics_00ee_bat:
      sensor_type: battery

