- platform: template
  sensors:
    air_pressure_template:
      friendly_name: 'Air Pressure'
      value_template: "{{ state_attr('weather.home','pressure') | default('1013') }}"
      unit_of_measurement: hPa
- platform: derivative
  source: sensor.baldr_b301_temp
  name: baldr_b301_delta
  round: 1
  unit: 'Celsius'
  time_window: "00:15:00"
- platform: filter
  name: baldr_b301_delta_avg
  entity_id: sensor.baldr_b301_delta
  filters:
    - filter: time_simple_moving_average
      window_size: "01:00"

