- platform: rest
  name: e5823_niveau_de_batterie
  resource: https://velo.netpascal.site/api/states/sensor.e5823_niveau_de_batterie
  value_template: "{{ value_json.state }}"
  unit_of_measurement: '%'
  headers:
    Authorization: !secret HOME_ASSISTANT_API_VELO
- platform: rest
  name: e5823_tracking
  resource: https://velo.netpascal.site/api/states/device_tracker.e5823
  value_template: "{{ value_json.state }}"
  json_attributes_path: "$.attributes"
  json_attributes:
    - source_type
    - latitude
    - longitude
    - gps_accuracy
    - altitude
    - course
    - speed
    - vertical_accuracy
  headers:
    Authorization: !secret HOME_ASSISTANT_API_VELO
