- platform: rest
  name: e5823_niveau_de_batterie
  resource: https://velo.netpascal.site/api/states/sensor.e5823_niveau_de_batterie
  value_template: "{{ value_json.state }}"
  unit_of_measurement: '%'
  headers:
    Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI5YjQ5NDhiZGVmNjc0OTYxYmQ2ZWY4ZGYzNDYwY2I3YiIsImlhdCI6MTYzMTk3Mjk1NywiZXhwIjoxOTQ3MzMyOTU3fQ.9LEQjd9AlKJEQitDma1eyt5am7XtOERmYsIFWN-LqIo
- platform: rest
  name: e5823_tracking
  resource: https://velo.netpascal.site/api/states/device_tracker.e5823
  value_template: "{{ value_json.state }}"
  json_attributes_path: "$.attributes"
  json_attributes:
    - source_type
    - latitude
    - longitude
    - gps_accuracy
    - altitude
    - course
    - speed
    - vertical_accuracy
  headers:
    Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI5YjQ5NDhiZGVmNjc0OTYxYmQ2ZWY4ZGYzNDYwY2I3YiIsImlhdCI6MTYzMTk3Mjk1NywiZXhwIjoxOTQ3MzMyOTU3fQ.9LEQjd9AlKJEQitDma1eyt5am7XtOERmYsIFWN-LqIo
