- platform: template
  sensors:
    bordeaux_temperature:
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('weather.bordeaux_2', 'temperature') }}"
    bordeaux_humidity:
      unit_of_measurement: '%'
      value_template: "{{ state_attr('weather.bordeaux_2', 'humidity') }}"
    home_temperature:
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('weather.home', 'temperature') }}"
    home_humidity:
      unit_of_measurement: '%'
      value_template: "{{ state_attr('weather.home', 'humidity') }}"

