- alias: Window left open
  trigger:
    platform: numeric_state
    entity_id: sensor.xiron_2102_temp
    below: 19
  condition:
    condition: or
    conditions:
       - condition: state
         entity_id: binary_sensor.openclose_9
         state: 'on'
       - condition: state
         entity_id: binary_sensor.openclose_10
         state: 'on'
  action:
    - service: notify.notify
      data:
        title: "Time to close window"
        message: "La temperature du living est de {{ states('sensor.xiron_2102_temp') }}"
    - service: persistent_notification.create
      data:
        title: "Time to close window"
        message: "La temperature du living est de {{ states('sensor.xiron_2102_temp') }}"
- alias: Baie left open
  trigger:
    platform: numeric_state
    entity_id: sensor.xiron_2102_temp
    below: 19
  condition:
    condition: or
    conditions:
       - condition: state
         entity_id: binary_sensor.openclose_8
         state: 'on'
  action:
    - service: notify.notify
      data:
        title: "Time to close window"
        message: "La temperature de la cuisine est de {{ states('sensor.xiron_2102_temp') }}"
    - service: persistent_notification.create
      data:
        title: "Time to close window"
        message: "La temperature de la cuisine est de {{ states('sensor.xiron_2102_temp') }}"
