- alias: Garden start
  trigger:
    - platform: sun
      event: sunset
    - platform: sun
      event: sunrise
  action:
    - service: light.toggle
      entity_id: light.ev1527_0dce12_08
    - delay: '00:01:00'
    - service: light.toggle                                                                                                                                                         
      entity_id: light.ev1527_0dce12_04   
    - delay: '00:01:00'
    - service: light.toggle            
      entity_id: light.ev1527_0dce12_04

