- alias: Tablette Low
  trigger:
    platform: numeric_state
    entity_id: sensor.sm_t800_battery_level
    below: 35
  condition:
    - condition: state
      entity_id: 'light.maclean_582f_01'
      state: 'off'
  action:
    - service: persistent_notification.create
      data:
        title: "Tablette"
        message: "La batterie de la tablette est a {{ states('sensor.sm_t800_battery_level') }}"
    - service: light.turn_on                                                                                                                                                      
      entity_id: light.maclean_582f_01
- alias: Tablette High                                                                                                                                                               
  trigger:                                                                                                                                                                          
    platform: numeric_state                                                                                                                                                         
    entity_id: sensor.sm_t800_battery_level                                                                                                                                         
    above: 90
  condition:
    - condition: state                                                                                                                                                                  
      entity_id: 'light.maclean_582f_01'                                                                                                                                              
      state: 'on'  
  action:                                                                                                                                                                           
    - service: persistent_notification.create                                                                                                                                       
      data:                                                                                                                                                                         
        title: "Tablette"                                                                                                                                                           
        message: "La batterie de la tablette est a {{ states('sensor.sm_t800_battery_level') }}"                                                                                    
    - service: light.turn_off
      entity_id: light.maclean_582f_01
    - delay: 15
    - service: light.turn_off
      entity_id: light.maclean_582f_01
