- alias: Tablette Low
  trigger:
    platform: numeric_state
    entity_id: sensor.sm_t835_battery_level_2
    below: 25
  condition:
    - condition: state
      entity_id: 'light.maclean_582f_01'
      state: 'off'
  action:
    - service: light.turn_on                                                                                                                                                      
      entity_id: light.maclean_582f_01
- alias: Tablette High
  trigger:
    platform: numeric_state
    entity_id: sensor.sm_t835_battery_level_2
    above: 95
  condition:
    - condition: state
      entity_id: 'light.maclean_582f_01'
      state: 'on' 
  action:
    - service: light.turn_off
      entity_id: light.maclean_582f_01
    - delay: '00:00:30'
    - service: light.turn_off
      entity_id: light.maclean_582f_01
