- alias: Allumer la lumiere quand la porte souvre
  trigger:
    - platform: state
      entity_id: binary_sensor.openclose_4
      to: 'on'
  action:
          #    - service: light.turn_on                                                                                                                                                      
          #      entity_id: light.color_temperature_light_7
          #      data_template:                                                                                                                                                                
          #        brightness: 250
    - service: light.turn_on
      entity_id: light.unitec_3aa3_01

