- alias: Allumer la lumiere quand la porte souvre
  trigger:
    - platform: state
      entity_id: binary_sensor.openclose_4
      to: 'on'
  action:
    - service: light.turn_on                                                                                                                                                      
      entity_id: light.dimmable_light_3
      data_template:                                                                                                                                                                
        brightness: 250
