- alias: Write Servo Tilt Value to ESP
  trigger:
    platform: state
    entity_id: input_number.servo_control_tilt
  action:
    - service: esphome.esp32cams_control_servo_tilt
      data_template:
        level: '{{ trigger.to_state.state | int }}'
